region_name = "us-east-1"
vpc_cidr_block = "10.0.0.0/16"
vpc_name = "dev-vpc"
igw_tag = "dev-igw" 
subnet_cidr_block = "10.0.0.0/24"
subnet_tag_name = "dev-subnet"
rt_cidr_block = "0.0.0.0/0"
rt_name = "dev-mrt"