region_name = "us-east-1"
vpc_cidr_block = "10.10.0.0/16"
vpc_name = "uat-vpc"
igw_tag = "uat-igw" 
subnet_cidr_block = "10.10.0.0/24"
subnet_tag_name = "uat-subnet"
rt_cidr_block = "0.0.0.0/0"
rt_name = "uat-mrt"