region_name = "us-east-1"
vpc_cidr_block = "10.10.0.0/16"
vpc_tag_name = "myvpc"
igw_tag_name = "igw"
subnet_cidr_block = "10.10.0.0/24"
subnet_tag_name = "public"
rt_cidr_block = "0.0.0.0/0"
rt_tag_name = "mrt"
