---
- hosts: all
  become: true

  tasks:
    - name: Installing Httpds server
      yum:
        name: httpd
        state: present

    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
